/* TeroSocial - La Feria, ampliación: vehículos, varios, animales e inmuebles */

window.AVISOS_C = [
  {
    id: 5400,
    vendedor: "young_bicicleteria",
    titulo: "Bicicleta rodado 26 usada, service hecho",
    categoria: "Vehículos",
    precio: 7200,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Entró en parte de pago y le hicimos el service completo antes de publicarla. Cuadro sano, 18 velocidades, cubiertas con dibujo. Es la primera de la izquierda en la foto, las otras no van. Si venis temprano te la dejamos regulada a tu altura, despues de las 17 estamos con el taller lleno.",
    ubicacion: "Young, Río Negro",
    publicado: "2026-06-02T09:30:00-03:00",
    contacto: "099 733 210",
    imagen: "media/fotos/bici_1.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "estudiante_utec", texto: "es de hombre o de mujer el cuadro?", fecha: "2026-06-02T18:20:00-03:00" },
      { autor: "young_bicicleteria", texto: "cuadro de caño alto, de hombre", fecha: "2026-06-03T09:10:00-03:00" },
      { autor: "elpibe.delcerro", texto: "6000 y la busco el sabado", fecha: "2026-06-04T23:40:00-03:00" }
    ]
  },
  {
    id: 5402,
    vendedor: "elpibe.delcerro",
    titulo: "skate electrico todo terreno, anda",
    categoria: "Vehículos",
    precio: 28000,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "vendo mi skate electrico, el de las ruedas de taco grande p andar x la calle y x tierra. tiene los 2 motores atras en el eje y la bateria va abajo de la tabla. la lija de arriba es la de panal q se ve en la foto, esta gastada de un lado nomas de tanto frenar con el pie. anda como 20 km cargado. me lo trajo un primo de afuera y no lo uso mas xq se me quemo el cargador original y ando con uno generico q carga mas lento pero carga. el control va incluido, le falta la tapita de las pilas. se retira x el cerro, cerca de la plaza. de mañana no existo, escribime de tarde",
    ubicacion: "Villa del Cerro, Montevideo",
    publicado: "2026-07-12T16:40:00-03:00",
    contacto: "wsp",
    imagen: "media/fotos/deporte_4.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "mama_de_tres_mvd", texto: "eso a que velocidad va? es para un gurí de 13 y me da miedo", fecha: "2026-07-12T21:00:00-03:00" },
      { autor: "elpibe.delcerro", texto: "si le das todo va rapido, pero tiene un modo lento para aprender", fecha: "2026-07-13T15:20:00-03:00" }
    ]
  },
  {
    id: 5403,
    vendedor: "guarda_101",
    titulo: "Pelota de basquet numero 7, poco uso",
    categoria: "Varios",
    precio: 1600,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "La compré para el sobrino y la usó dos veces. Es la número 7, naranja con las tiras blancas, de las de cuero sintético para cancha techada. La foto es la que le saqué arriba del mostrador el día que la compré, está igual, tiene una rozadura en un gajo y nada más. Tengo el ticket. La tengo en Colón, a dos cuadras de la escuela. Vení entre las 14 y las 18 que después salgo.",
    ubicacion: "Colón, Montevideo",
    publicado: "2026-03-19T14:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/deporte_2.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "laura.rambla", texto: "Sirve para jugar en la calle? Es para la escuela.", fecha: "2026-03-20T19:30:00-03:00" },
      { autor: "guarda_101", texto: "en el pavimento se te pela en dos semanas. Esa es de piso de parquet", fecha: "2026-03-21T07:45:00-03:00" }
    ]
  },
  {
    id: 5404,
    vendedor: "laura_rambla",
    titulo: "Patines en linea de nena regulables, con casco y protecciones",
    categoria: "Varios",
    precio: 2200,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Se los regalé a mi sobrina para el cumpleaños y le duraron un verano, ahora quiere hacer natación. Son rosados con celeste, regulables corriendo la traba de abajo, van del 30 al 33. Va todo el juego que se ve en la foto: el casco rosado, las rodilleras y las coderas, todo con los dibujitos de unicornios y arcoíris. Las ruedas están enteras, la de adelante del pie derecho está un poco comida de frenar. Se ve por Malvín, coordino de noche que de dia trabajo.",
    ubicacion: "Malvín, Montevideo",
    publicado: "2026-07-22T21:10:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/deporte_1.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "mateamargo_87", texto: "sirven para un gurí de 8? o son muy de nena", fecha: "2026-07-23T07:00:00-03:00" },
      { autor: "laura_rambla", texto: "de talle le van a andar, pero son rosados y con unicornios. Vos verás", fecha: "2026-07-23T20:30:00-03:00" }
    ]
  },
  {
    id: 5405,
    vendedor: "esceptico_uy",
    titulo: "Sillita de bebe para bici, va montada atras",
    categoria: "Varios",
    precio: 1900,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Era del gurí y ya no entra, hace dos años que junta polvo en el garage. Es de las que van atrás, montadas sobre el caño del asiento. Respaldo alto, arnés de tres puntas con la traba roja en el medio y los dos apoyapiés con la correa. La almohadilla gris del asiento se saca y se lava. En la foto la estoy limpiando justamente para publicarla, el trapo no va incluido. Está en Sayago, atiendo casi siempre despues de las 20 porque de dia estoy con la planilla. No hago envios ni entrego en el centro.",
    ubicacion: "Sayago, Montevideo",
    publicado: "2025-11-12T20:40:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/bici_14.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "vecina.malvin.rosa", texto: "Buenas tardes. Sigue disponible? El aviso figura con fecha del año pasado.", fecha: "2026-06-28T11:20:00-03:00" }
    ]
  },
  {
    id: 5406,
    vendedor: "young_bicicleteria",
    titulo: "Bicicleta rodado 16 para nene, roja",
    categoria: "Vehículos",
    precio: 3900,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Rodado 16, para gurí de 4 a 6 años. Roja y gris, con canasto de alambre adelante, parrilla atras, guardabarros y cubre cadena. Entró usada y le hicimos el service: cámaras nuevas, frenos regulados y una mano de grasa en los rulemanes. Las rueditas de atras no vienen, el que la trajo ya andaba sin ellas, si las querés te las conseguimos por 400 mas. Le falta el timbre. Se ve en el local y te la dejamos regulada a la altura del gurí.",
    ubicacion: "Young, Río Negro",
    publicado: "2026-06-25T10:00:00-03:00",
    contacto: "099 733 210",
    imagen: "media/fotos/bici_12.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5407,
    vendedor: "feriante_tristan",
    titulo: "Triciclo dinosaurio para nene chico, sin caja",
    categoria: "Varios",
    precio: 2400,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Me trajeron una docena de estos el domingo. Es el triciclo verde con forma de dinosaurio, la rueda grande adelante y las dos chiquitas atras, y la boca del bicho se abre y se cierra. Para nene de dos a cuatro años. Vienen sin caja y sin papel ninguno, la foto es la que me pasó el muchacho que me los trajo. No pregunto de donde viene la mercaderia, yo compro lo que me traen y lo vendo. Precio por unidad, llevando dos hago precio. Entrego los martes en la feria del barrio o el domingo en la grande.",
    ubicacion: "Cordón, Montevideo",
    publicado: "2026-04-11T08:20:00-03:00",
    contacto: "099 208 774",
    imagen: "media/fotos/bici_13.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "young_bicicleteria", texto: "esa foto es la del catalogo del importador, con el fondo blanco y todo. No es una foto tuya", fecha: "2026-04-11T15:00:00-03:00" },
      { autor: "feriante_tristan", texto: "yo compro lo que me traen, no soy la policia", fecha: "2026-04-11T16:30:00-03:00" },
      { autor: "escepticouy", texto: "Doce juguetes iguales, sin caja y con la foto del catálogo. El que compra sabiendo también participa.", fecha: "2026-04-12T10:15:00-03:00" }
    ]
  },
  {
    id: 5408,
    vendedor: "hacker.del.prado",
    titulo: "bici rodado 20 gris y roja, sin numero de cuadro",
    categoria: "Vehículos",
    precio: 5200,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "bici rodado 20 gris con las letras rojas, freno a disco adelante y cambios atras. me la dio un pibe del liceo por una consola. en la foto esta acostada contra la pared xq le falta el pie y no para sola, no es q este rota. anda todo, hay q ajustarle un poco los cambios q se pasan. abajo del pedalier, donde va grabado el numero, esta lijado. yo no lo lije, me llego asi. no pidan papeles xq no hay. entrego en la plaza del Prado, de tarde",
    ubicacion: "Prado, Montevideo",
    publicado: "2026-05-30T22:15:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/bici_9.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "hacker_del_prado", texto: "Pibe, una bici con el número del cuadro lijado es una bici que alguien no quiere que se identifique. Bajá el aviso.", fecha: "2026-05-31T01:40:00-03:00" },
      { autor: "hacker.del.prado", texto: "otra vez me confunden con vos jaja. igual yo no la lije, me la dieron asi", fecha: "2026-05-31T14:00:00-03:00" },
      { autor: "moderacion_terosocial", texto: "Aviso en revisión. Se solicitó información adicional al publicante.", fecha: "2026-06-02T09:00:00-03:00" }
    ]
  },
  {
    id: 5409,
    vendedor: "laspiedras_mecanico",
    titulo: "Sedan antiguo bordo restaurado, motor rectificado",
    categoria: "Vehículos",
    precio: 7400,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Otro que armé en el taller de a poco. Es el sedán bordó de cuatro puertas de la foto, con los paragolpes cromados y las llantas de aleación. Motor rectificado, embrague nuevo, frenos hechos. Chapa derecha, la pintura la mandé a hacer del color original y quedó pareja. Empadronado, libreta y patente al dia. La chapa la tapé en la foto, la matrícula te la paso por privado si venis en serio. La foto se la saqué el dia que lo probé por el camino de un cliente. No permuto por motos ni por bicis.",
    ubicacion: "Las Piedras, Canelones",
    publicado: "2026-02-10T09:00:00-03:00",
    contacto: "099 412 887",
    imagen: "media/fotos/auto_14.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "taxi_cx_1420", texto: "cuantos km declara el cuentakilometros?", fecha: "2026-02-10T13:30:00-03:00" },
      { autor: "laspiedras_mecanico", texto: "el cuentakilometros de estos autos viejos no dice nada, dio la vuelta dos veces. Miralo por abajo que es lo que importa", fecha: "2026-02-10T18:00:00-03:00" },
      { autor: "contadora.gimenez", texto: "Tiene deuda de patente? Porque eso después lo paga el comprador.", fecha: "2026-02-14T17:20:00-03:00" },
      { autor: "laspiedras_mecanico", texto: "cero deuda, te muestro el papel", fecha: "2026-02-15T08:40:00-03:00" }
    ]
  },
  {
    id: 5410,
    vendedor: "taxi_cx_1420",
    titulo: "Auto sedan de trabajo, anda bien",
    categoria: "Vehículos",
    precio: 5200,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Auto que usé de apoyo cuando el movil estaba en el taller. Anda bien, gasta poco, la caja entra suave. Tiene los años que tiene y se nota en el tapizado. Es el que esta de frente en la foto. Lo tengo en la Unión, cerca de la parada. Vendo porque compré otro, no por problemas.",
    ubicacion: "Unión, Montevideo",
    publicado: "2026-06-05T11:20:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/auto_3.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "remis_nocturno_mvd", texto: "sirve para trabajar de noche? te pregunto en serio", fecha: "2026-06-05T23:50:00-03:00" },
      { autor: "taxi_cx_1420", texto: "sirve, pero hacele el tren delantero primero", fecha: "2026-06-06T08:10:00-03:00" },
      { autor: "elpibe.delcerro", texto: "carisimo eso", fecha: "2026-06-07T02:30:00-03:00" }
    ]
  },
  {
    id: 5412,
    vendedor: "mateamargo87",
    titulo: "Cupe deportivo negro, dos puertas",
    categoria: "Vehículos",
    precio: 26000,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Ya se que no es un auto de alguien que anda repartiendo, y no, no es mio de toda la vida: me quedó de un arreglo con un cuñado que se fue del pais y precisaba la plata en la mano. Es el cupé negro de la foto, dos puertas, motor grande, llantas de aleación grandes y los vidrios oscuros. Anda impecable y lo tengo bajo techo. Nafta, y toma la que toma, no vengas a preguntarme el consumo. Empadronado en Cerro Largo, papeles al dia, transferencia hecha. La chapa la tapé en la foto, te la paso por privado. Se ve en Melo, cerca de la terminal vieja.",
    ubicacion: "Melo, Cerro Largo",
    publicado: "2026-07-01T19:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/auto_12.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5413,
    vendedor: "charrua_libre",
    titulo: "Auto rojo tres puertas, lo vendo por partes",
    categoria: "Vehículos",
    precio: 62000,
    moneda: "UYU",
    estado_articulo: "para repuesto",
    descripcion: "Hatchback rojo, tres puertas, de los de los noventa. Anda, arranca y camina, lo saqué a la vuelta para sacarle la foto en el pedregullo. Chapa sana arriba, abajo de las puertas tiene principio de oxido. No tiene libreta ni la voy a conseguir. Por eso lo vendo como partes: motor, caja, puertas, tren delantero, lo que precises. El que quiera venir a sacarle algo que traiga herramienta propia. Coordino el punto, no doy direccion por acá. Efectivo. No pregunto para que lo queres y no me preguntes de donde salió.",
    ubicacion: "Montevideo",
    publicado: "2026-04-22T21:30:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/auto_11.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "laspiedras_mecanico", texto: "sin libreta no lo toco, ni entero ni en pedazos. Ya me pasó una vez y no me pasa mas", fecha: "2026-04-23T08:00:00-03:00" },
      { autor: "escepticouy", texto: "Un auto que arranca y camina no se vende por partes. Se vende por partes cuando lo que molesta es el auto entero.", fecha: "2026-04-23T12:40:00-03:00" },
      { autor: "charrua_libre", texto: "el que entiende entiende. el resto que siga de largo", fecha: "2026-04-23T23:10:00-03:00" }
    ]
  },
  {
    id: 5414,
    vendedor: "tero_anon_2018",
    titulo: "Casco integral negro talle L, sin caja ni factura",
    categoria: "Vehículos",
    precio: 3400,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Casco integral negro mate, talle L, con el visor todavia con el nylon puesto y la etiqueta colgando. Me quedaron tres de un lote que le compré a un muchacho que los traia, caja no vino con ninguno y factura tampoco, no me la pidan. El de la foto es el ultimo que queda. Retira el comprador, Paysandu.",
    ubicacion: "Paysandú, Paysandú",
    publicado: "2026-06-18T07:50:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/moto_4.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "laspiedras_mecanico", texto: "un casco sin caja no se sabe de que año es ni si se pegó contra el piso alguna vez", fecha: "2026-06-18T09:30:00-03:00" },
      { autor: "contadora.gimenez", texto: "Un casco es lo último que yo compraría sin saber de dónde salió. Es lo que te sostiene la cabeza.", fecha: "2026-06-18T16:00:00-03:00" },
      { autor: "tero_anon_2018", texto: "esta sin usar muchachos, se ve en la foto que tiene el nylon todavia", fecha: "2026-06-19T08:20:00-03:00" },
      { autor: "hacker_del_prado", texto: "La etiqueta de certificación se compra suelta por dos pesos. La que no se falsifica es la del lote adentro de la calota, y esa no la mostrás.", fecha: "2026-06-19T23:40:00-03:00" }
    ]
  },
  {
    id: 5415,
    vendedor: "laspiedras_mecanico",
    titulo: "Cubierta 185/55 R15, una sola",
    categoria: "Vehículos",
    precio: 2600,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Me quedó una sola de un juego que cambié en el taller. Es 185/55 R15, japonesa, le queda como el setenta por ciento de dibujo y no tiene ningun parche. La medida se la escribí con tiza para no confundirla con las otras que tengo apiladas. Sirve de auxilio o para completar juego. Sabado solo de mañana.",
    ubicacion: "Las Piedras, Canelones",
    publicado: "2026-07-08T08:15:00-03:00",
    contacto: "099 412 887",
    imagen: "media/fotos/ruta_6.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "guarda_101", texto: "no tenes otra igual? preciso las dos de adelante", fecha: "2026-07-08T14:20:00-03:00" },
      { autor: "laspiedras_mecanico", texto: "en esa medida me quedó esa nomas. Si cae otra te aviso", fecha: "2026-07-08T18:45:00-03:00" }
    ]
  },
  {
    id: 5416,
    vendedor: "laspiedras_mecanico",
    titulo: "REPUBLICO sedan antiguo restaurado, bajé el precio",
    categoria: "Vehículos",
    precio: 6900,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Republico el mismo auto de hace unos meses porque no aparecio nadie serio. Es el mismo, otra foto, ahora de frente. Motor rectificado, embrague nuevo, papeles al dia. Bajé 500 dolares y de ahi no me muevo. Sigue en la vereda del taller. Los que preguntaron y no vinieron, no insistan.",
    ubicacion: "Las Piedras, Canelones",
    publicado: "2026-05-20T08:30:00-03:00",
    contacto: "099 412 887",
    imagen: "media/fotos/auto_1.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "mateamargo_87", texto: "no es el mismo que tenias publicado en febrero?", fecha: "2026-05-20T12:00:00-03:00" },
      { autor: "laspiedras_mecanico", texto: "el mismo. Lo republico porque el otro aviso ya lo miraba nadie", fecha: "2026-05-20T13:15:00-03:00" },
      { autor: "laspiedras_mecanico", texto: "VENDIDO. gracias", fecha: "2026-06-30T17:00:00-03:00" }
    ]
  },
  {
    id: 5418,
    vendedor: "mateamargo87",
    titulo: "Criques hidraulicos de piso nuevos, 3 toneladas",
    categoria: "Vehículos",
    precio: 3900,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Criques de piso hidraulicos de tres toneladas, nuevos, sin abrir. Vienen en la caja de cartón con el telgopor y las dos partes de la manija al costado, tal cual la foto que le saqué al primero que abrí. Levantan auto chico y camioneta sin problema. Me quedaron cuatro de un lote que traje del norte. Factura no hay ni va a haber, no me la pidan. Precio por unidad. Se retira por Melo, atiendo despues de las 19 que antes estoy repartiendo.",
    ubicacion: "Melo, Cerro Largo",
    publicado: "2025-12-03T18:20:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/ruta_10.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "contadora.gimenez", texto: "Sin factura no hay garantía ni hay nada. Y si el aparato falla, el problema lo tiene el que está abajo del auto.", fecha: "2025-12-04T10:30:00-03:00" },
      { autor: "mateamargo87", texto: "señora es un crique, no es un auto robado. Lo prueba y lo lleva", fecha: "2025-12-04T19:00:00-03:00" },
      { autor: "taxi_cx_1420", texto: "un crique sin marca ni papeles se te viene abajo con el auto arriba. Yo no me meto abajo de eso ni loco", fecha: "2025-12-05T08:15:00-03:00" },
      { autor: "estudiante_utec", texto: "sigue disponible? vi que el aviso es de diciembre", fecha: "2026-07-11T23:40:00-03:00" }
    ]
  },
  {
    id: 5419,
    vendedor: "el.tero.viajero",
    titulo: "Llantas de aleación con cubiertas todo terreno, juego de 4",
    categoria: "Vehículos",
    precio: 34000,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Las sacamos de la camioneta de las excursiones cuando le volvimos a poner las de fábrica. Son cuatro llantas de aleación negras con el borde diamantado y cubiertas todo terreno de las de taco grande. Dibujo les queda bastante, la que está en la foto es justo la más gastada de las cuatro. Van sucias de la tierra colorada de los caminos de Rocha, se lavan y quedan como nuevas. Se retira por La Paloma, no mandamos por encomienda.",
    ubicacion: "La Paloma, Rocha",
    publicado: "2026-05-02T10:50:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/ruta_5.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5420,
    vendedor: "melo_ferretero",
    titulo: "Bicicleta rodado 26 que quedó en el local",
    categoria: "Vehículos",
    precio: 5900,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Un cliente la dejó a cuenta de una cuenta que tenia conmigo y nunca la vino a buscar. Es de montaña, rodado 26, con suspension adelante. Anda bien, la probé yo por la vereda. La tengo atras del mostrador ocupando lugar. No hago descuento y no la mando por encomienda.",
    ubicacion: "Melo, Cerro Largo",
    publicado: "2026-02-17T09:40:00-03:00",
    contacto: "099 641 305",
    imagen: "media/fotos/bici_6.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "mateamargo87", texto: "carlos esa no era del muchacho del taller?", fecha: "2026-02-17T20:00:00-03:00" },
      { autor: "melo_ferretero", texto: "era. Me debia desde el año pasado. Preguntá menos y comprá mas", fecha: "2026-02-18T08:20:00-03:00" }
    ]
  },
  {
    id: 5421,
    vendedor: "dona_elsa_74",
    titulo: "BICICLETA CHIQUITA DE MI NIETA, CON RUEDITAS",
    categoria: "Vehículos",
    precio: 1600,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "BUENAS TARDES VECINOS. VENDO LA BICICLETA DE MI NIETA LA CHICA QUE YA CRECIO Y ANDA EN UNA GRANDE. ES ROSADA CON EL CANASTITO ADELANTE, EL ASIENTO CELESTE Y LAS RUEDITAS DE ATRAS TODAVIA PUESTAS. TIENE UNAS CALCOMANIAS DE UNAS PRINCESAS DEL DIBUJITO, HAY UNA QUE ESTA MEDIO DESPEGADA. ESTABA EN EL GALPON DEL FONDO Y LA LAVE PARA SACARLE LA FOTO. LE FALTA UN TAPON DE LA MANIJA. ESTOY EN PAYSANDU A UNA CUADRA DE LA IGLESIA. SI ESCRIBO GRANDE ES PORQUE VEO POCO. DIOS LOS BENDIGA.",
    ubicacion: "Paysandú, Paysandú",
    publicado: "2026-06-14T15:30:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/bici_11.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "tero_anon_2018", texto: "doña es justo para mi sobrina, yo vivo cerca. Paso el sabado a verla", fecha: "2026-06-14T18:00:00-03:00" },
      { autor: "dona_elsa_74", texto: "GRACIAS HIJO TE ESPERO DESPUES DE LAS 10 QUE ANTES ESTOY EN MISA", fecha: "2026-06-15T09:10:00-03:00" }
    ]
  },
  {
    id: 5423,
    vendedor: "ojos_cerrados_uy",
    titulo: "Bicicleta rodado 26 con suspension, nos quedó de un cambio",
    categoria: "Vehículos",
    precio: 6400,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Nos la dejaron a cuenta de una fecha que no nos pagaron y quedó en la sala de ensayo. Es rodado 26, cuadro plateado con azul, suspension adelante y cambios en los dos lados. Anda y frena, está sucia de estar guardada contra la pared, se ve en la foto. No sabemos mucho de bicis. Abajo, donde nos dicen que va grabado el numero, no se lee nada. La entregamos como está. Coordinamos por mensaje, tocamos casi todos los viernes.",
    ubicacion: "Montevideo",
    publicado: "2026-07-18T23:50:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/bici_10.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "young_bicicleteria", texto: "el numero va grabado abajo del pedalier y no se borra solo. Si no se lee, algo pasó ahi", fecha: "2026-07-19T09:30:00-03:00" },
      { autor: "escepticouy", texto: "Vender algo que no sabés de dónde salió es una posición cómoda hasta que deja de serlo.", fecha: "2026-07-19T15:00:00-03:00" },
      { autor: "ojos_cerrados_uy", texto: "nosotros solo tocamos la guitarra amigo", fecha: "2026-07-20T01:20:00-03:00" }
    ]
  },
  {
    id: 5426,
    vendedor: "charrua_libre",
    titulo: "Auto andando, sin papeles, se entrega como esta",
    categoria: "Vehículos",
    precio: 48000,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Anda, arranca y camina. No tiene libreta ni transferencia, se entrega como esta y despues cada uno vera. Precio bajo justamente por eso. No respondo llamadas ni doy direccion, coordinamos punto de encuentro de dia. Efectivo. El que pregunta de mas no compra.",
    ubicacion: "Montevideo",
    publicado: "2026-06-29T06:40:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/auto_2.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "contadora.gimenez", texto: "Un auto sin documentación no es tuyo para venderlo. Eso no es una opinión.", fecha: "2026-06-29T11:00:00-03:00" },
      { autor: "taxi_cx_1420", texto: "veintiocho años arriba de un auto y nunca vi que esto terminara bien para el que compra", fecha: "2026-06-29T14:30:00-03:00" },
      { autor: "moderacion_terosocial", texto: "Aviso reportado. En revisión conforme a las normas de la comunidad.", fecha: "2026-06-30T10:00:00-03:00" }
    ]
  },
  {
    id: 5427,
    vendedor: "melo_ferretero",
    titulo: "Camion chico con furgon, el del reparto del local",
    categoria: "Vehículos",
    precio: 12500,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Camion chico, cabina blanca y furgón amarillo atras, de los de una tonelada y media. Es el que usaba para traer la mercaderia de Montevideo hasta que empecé a mandar todo por transporte. Motor sano, caja entera, gomas al sesenta por ciento. El furgón tiene abolladuras y oxido en los bordes de abajo, se ve en la foto, no lo pinté para no venderte humo. Empadronado en Cerro Largo, papeles al dia. La chapa la tapé en la foto, te la paso por privado. Está atras del local, lunes a viernes de 8 a 12 y de 14 a 19.",
    ubicacion: "Melo, Cerro Largo",
    publicado: "2026-05-06T10:30:00-03:00",
    contacto: "099 641 305",
    imagen: "media/fotos/auto_13.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "camionero_ruta5", texto: "CUANTO CARGA EXACTAMENTE ESE FURGON", fecha: "2026-05-06T14:00:00-03:00" },
      { autor: "melo_ferretero", texto: "lo que le pongas arriba y siga andando. Pasá y lo mirás", fecha: "2026-05-06T15:20:00-03:00" },
      { autor: "camionero_ruta5", texto: "eso no es un dato Carlos", fecha: "2026-05-07T04:40:00-03:00" }
    ]
  },
  {
    id: 5428,
    vendedor: "elpibe.delcerro",
    titulo: "REPUBLICO la tabla de skate sola, nadie la quiso",
    categoria: "Varios",
    precio: 900,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "la republico xq nadie vino. es la tabla sola, sin ejes ni ruedas, lo aclaro antes de q pregunten. la lija esta gastada en el medio y se ve la madera x los bordes, pero la tabla esta sana, no se despego ninguna capa. la tengo parada atras de la puerta como sale en la foto. baje 600 y de ahi no bajo mas. se retira x el cerro cerca de la plaza. dsp de las 15 q antes duermo",
    ubicacion: "Villa del Cerro, Montevideo",
    publicado: "2026-07-30T15:20:00-03:00",
    contacto: "wsp",
    imagen: "media/fotos/deporte_3.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5431,
    vendedor: "artesano_piriapolis",
    titulo: "Tablas de asado con incrustación, hechas a mano",
    categoria: "Varios",
    precio: 1450,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Tablas de picada y de asado que armo yo con recortes de pino y de madera colorada. La guarda del medio va encastrada pieza por pieza, no es calcomanía ni pintura, por eso ninguna sale igual a la otra. Llevan el mango con el agujero para colgar y van terminadas con aceite de uso alimenticio. En la foto están las cuatro que tengo hechas, el precio es el de la mediana. Las tengo en el puesto de la feria los fines de semana, si llueve no bajo.",
    ubicacion: "Piriápolis, Maldonado",
    publicado: "2026-05-21T11:20:00-03:00",
    contacto: "099 567 220",
    imagen: "media/fotos/comida_9.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "colonia_guia_turismo", texto: "hacés por encargo? me piden souvenirs los grupos y estas quedan lindas", fecha: "2026-05-21T17:00:00-03:00" },
      { autor: "artesano_piriapolis", texto: "hago pero con dos semanas de anticipacion minimo, la madera colorada tiene que descansar", fecha: "2026-05-22T09:30:00-03:00" }
    ]
  },
  {
    id: 5433,
    vendedor: "rivera_frontera",
    titulo: "Mates de calabaza chicos, por docena",
    categoria: "Varios",
    precio: 8800,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Docena de mates chicos con virola, traidos de la otra banda. Vienen sin factura porque cruzan de a poco, no me pregunten mas que eso. Sirven para revender en feria o para regalar en la empresa. Precio por la docena. Solo por encomienda o si venis a Rivera. Pago adelantado, no fio.",
    ubicacion: "Rivera, Rivera",
    publicado: "2026-04-15T13:30:00-03:00",
    contacto: "099 855 401",
    imagen: "media/fotos/mate_2.jpg",
    vendido: true,
    turbio: true,
    consultas: [
      { autor: "contadora.gimenez", texto: "Sin factura no podés revenderlo en un comercio. Después el problema lo tiene el que compra.", fecha: "2026-04-15T18:40:00-03:00" },
      { autor: "rivera_frontera", texto: "es para uso personal patricia, yo no digo nada mas", fecha: "2026-04-16T09:00:00-03:00" },
      { autor: "escepticouy", texto: "Una docena no es uso personal salvo que tengas doce manos.", fecha: "2026-04-16T14:20:00-03:00" }
    ]
  },
  {
    id: 5437,
    vendedor: "elrusodelquiosco",
    titulo: "Cocinas a leña de chapa, hay dos medidas",
    categoria: "Varios",
    precio: 14800,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Las hace un vecino que tiene la herrería a la vuelta y yo le doy una mano vendiendolas, por eso el aviso sale a mi nombre. Son de chapa gruesa, con horno, cajón de cenizas y la boca para el caño, pintadas con pintura de alta temperatura. El precio es el de la chica, la grande de la foto sale 26500. El caño no va incluido. Se retira por Goes y hay que venir con camioneta y con alguien que ayude, pesan un disparate. Abro a las 7 y cierro a las 23, elegí vos.",
    ubicacion: "Goes, Montevideo",
    publicado: "2025-10-08T09:20:00-03:00",
    contacto: "099 774 118",
    imagen: "media/fotos/hogar_2.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "feriante_tristan", texto: "ruso la grande sola cuanto me la dejas", fecha: "2025-10-08T13:00:00-03:00" },
      { autor: "elrusodelquiosco", texto: "26500 Oscar, y si llevás las dos te hago 38 y no hablo mas", fecha: "2025-10-08T14:15:00-03:00" },
      { autor: "pintor_rodri", texto: "sigue disponible esto?", fecha: "2026-05-30T18:40:00-03:00" }
    ]
  },
  {
    id: 5439,
    vendedor: "elrusodelquiosco",
    titulo: "Cama de una plaza con carro abajo y respaldo con estante",
    categoria: "Varios",
    precio: 9600,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Es la cama del gurí, que se fue a vivir solo y me la dejó tirada en el deposito. Una plaza, con el carro que sale de abajo asi que si te queda alguien a dormir la corrés y tenés dos. El respaldo trae el estantecito al costado, es todo el mismo mueble. Tiene un golpe en la pata de atras que no se ve cuando está contra la pared. Los colchones no van. Se retira por Goes, temprano que a la tarde estoy solo en el mostrador.",
    ubicacion: "Goes, Montevideo",
    publicado: "2026-05-13T08:40:00-03:00",
    contacto: "099 774 118",
    imagen: "media/fotos/mueble_13.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "pintor_rodri", texto: "el carro de abajo tiene ruedas o hay que arrastrarlo?", fecha: "2026-05-13T12:00:00-03:00" },
      { autor: "elrusodelquiosco", texto: "cuatro ruedas de goma, sale sola de un tirón. Se traba con la mano nomas", fecha: "2026-05-13T13:30:00-03:00" }
    ]
  },
  {
    id: 5440,
    vendedor: "patriota_oriental_1811",
    titulo: "VENTANA DE ALUMINIO CORREDIZA CON LOS VIDRIOS PUESTOS",
    categoria: "Varios",
    precio: 4700,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "VENTANA CORREDIZA DE DOS HOJAS, ALUMINIO NATURAL, CON LOS DOS VIDRIOS SANOS Y LAS MANIJAS NEGRAS PUESTAS. MIDE MAS O MENOS METRO CUARENTA POR METRO CUARENTA, VENGAN CON EL METRO Y MIDANLA USTEDES QUE YO DE ESO NO ENTIENDO. ME LA TRAJERON DE UNA OBRA QUE PARARON, NO PREGUNTO DE DONDE VIENE NI ME INTERESA. RETIRA EL COMPRADOR EN CANELONES, COORDINO PUNTO.",
    ubicacion: "Canelones",
    publicado: "2026-07-11T07:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/construccion_11.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "melo_ferretero", texto: "una ventana entera y con los vidrios sanos no queda tirada en ninguna obra parada. Eso lo sabe cualquiera", fecha: "2026-07-11T09:40:00-03:00" },
      { autor: "escepticouy", texto: "No preguntar de dónde viene es una decisión, no una casualidad.", fecha: "2026-07-11T16:20:00-03:00" },
      { autor: "patriota_oriental_1811", texto: "SIEMPRE LOS MISMOS JUZGANDO AL QUE TRABAJA", fecha: "2026-07-12T06:30:00-03:00" }
    ]
  },
  {
    id: 5441,
    vendedor: "melo_ferretero",
    titulo: "Porta mate impreso en 3D, para hinchas",
    categoria: "Varios",
    precio: 590,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Me los dejó en consignación un muchacho que tiene una impresora de esas 3D en la casa. Es el soporte para el mate, con la manija arriba para levantarlo sin quemarse y la base azul. Va rojo y azul con el escudo del cuadro adelante, en la foto se ve el que tengo de muestra. Tengo doce, hay de un cuadro solo. Cuando se terminan no repongo, esto no es mi rubro. Vení, mirá y llevá.",
    ubicacion: "Melo, Cerro Largo",
    publicado: "2026-01-16T09:30:00-03:00",
    contacto: "099 641 305",
    imagen: "media/fotos/mate_12.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5443,
    vendedor: "tambero_sanjose",
    titulo: "Apoya caña para clavar en la arena, de hierro",
    categoria: "Varios",
    precio: 680,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Lo hice yo con hierro planchuela y dos aros soldados, para clavar en la arena y dejar la caña sin que se llene de tierra. Va pintado de amarillo con esmalte sintetico para verlo de lejos cuando ya oscureció. Aguanta caña de costa con reel grande, la punta entra sola en la arena mojada. Tengo tres iguales, el precio es de uno. Bajo a Kiyú los domingos temprano y te lo puedo llevar. Escribo a las cinco de la mañana porque ya trabajé dos horas.",
    ubicacion: "San José, San José",
    publicado: "2026-05-04T05:10:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/pesca_6.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "productor_durazno", texto: "en la ferreteria de Melo los vendian hechos a mil quinientos. No te regales Ernesto", fecha: "2026-05-04T18:30:00-03:00" },
      { autor: "tambero_sanjose", texto: "y bueno, a mi el hierro no me costó nada, salió de un porton que corté", fecha: "2026-05-05T05:00:00-03:00" }
    ]
  },
  {
    id: 5445,
    vendedor: "productor_durazno",
    titulo: "Rollo de tejido romboidal que sobró del galpón",
    categoria: "Varios",
    precio: 3800,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Cerré el costado del galpón con tejido y me sobró este rollo. Es romboidal galvanizado, de metro ochenta de alto, calculo que quedan ocho o nueve metros. Está sano, ni una malla rota, va con un poco de alambre de atar. Lo tengo parado contra la pared tal cual la foto. Se lleva asi como está, hay que venir con carro que suelto no se puede llevar.",
    ubicacion: "Durazno, Durazno",
    publicado: "2026-03-27T06:50:00-03:00",
    contacto: "099 158 340",
    imagen: "media/fotos/construccion_9.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "treintaytres_jinete", texto: "cuantos metros tiene exacto? no lo mediste?", fecha: "2026-03-27T19:00:00-03:00" },
      { autor: "productor_durazno", texto: "no lo medi, lo calculo de ojo. Vení y lo estiramos en el piso", fecha: "2026-03-28T06:10:00-03:00" }
    ]
  },
  {
    id: 5448,
    vendedor: "pescador_delaplata",
    titulo: "Lancha 4.60 con motor y trailer",
    categoria: "Vehículos",
    precio: 6800,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Lancha de 4.60, casco blanco con la franja negra, parabrisas sano y la lona. Motor fuera de borda chico, arranca a la primera. Va con el trailer que se ve en la foto, con la rueda de apoyo adelante. Papeles de la lancha y del trailer al dia. La matricula la tapé en la foto, te la paso por privado. La foto es del dia que la lavé, parada en la calle del pueblo. Está en Kiyú. Si hay viento del sur no atiendo, estoy pescando.",
    ubicacion: "Kiyú, San José",
    publicado: "2026-06-16T06:30:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/nautica_3.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "pescador_tacuarembo", texto: "Julio vos vendiendo la lancha? no lo puedo creer primo", fecha: "2026-06-16T11:00:00-03:00" },
      { autor: "pescador_delaplata", texto: "ya no la bajo mas. Se me terminó la espalda, pesco de costa nomas", fecha: "2026-06-16T13:20:00-03:00" }
    ]
  },
  {
    id: 5449,
    vendedor: "tero_anon_2018",
    titulo: "Motor fuera de borda antiguo de 5 HP, para restaurar",
    categoria: "Varios",
    precio: 4500,
    moneda: "UYU",
    estado_articulo: "para repuesto",
    descripcion: "Motor fuera de borda viejo, de 5 caballos, pintado de verde agua. Estaba en el fondo del galpon de la barraca desde antes de que yo entrara a trabajar y nadie lo reclamó nunca. Tiene oxido en el pie y en los soportes, la tapa del tanque de arriba está sana y todavia se lee el numero. No lo probé en el agua ni sé si arranca, lo digo derecho. Lo tengo apoyado en un caballete en el patio, tal cual la foto. Sirve para restaurar o para sacarle piezas. Papeles no hay. Estoy en Paysandu, entrego en la barraca donde trabajo, de lunes a viernes hasta las 17.",
    ubicacion: "Paysandú, Paysandú",
    publicado: "2026-05-27T18:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/nautica_4.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "pescador_tacuarembo", texto: "esos motorcitos arrancan siempre, el tema es conseguirle el impulsor", fecha: "2026-05-27T20:40:00-03:00" },
      { autor: "tero_anon_2018", texto: "y... esta viejo. Yo lo vendo como esta, ni lo intenté arrancar", fecha: "2026-05-28T08:00:00-03:00" }
    ]
  },
  {
    id: 5453,
    vendedor: "elpibe.delcerro",
    titulo: "2 tambores de candombe, los vendo juntos",
    categoria: "Varios",
    precio: 13500,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "vendo los 2 tambores q estan en la foto, el blanco esta pintado a mano y tiene las iniciales del dueño de antes en el costado, el otro es de duela barnizada con los aros cromados. los dos con lonja sana y afinada, suenan los 2. no van las correas ni los palos, eso me lo quedo. los tengo arriba del banco en la casa de mi tio. se retiran x el cerro, escribime de tarde q de mañana no existo",
    ubicacion: "Villa del Cerro, Montevideo",
    publicado: "2026-07-09T17:30:00-03:00",
    contacto: "wsp",
    imagen: "media/fotos/murga_5.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5455,
    vendedor: "dona_elsa_74",
    titulo: "TORTAS FRITAS CASERAS, HAGO POR ENCARGO",
    categoria: "Varios",
    precio: 45,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "HAGO TORTAS FRITAS POR ENCARGO, IGUALITAS A LAS DE LA FOTO QUE SALIERON EL DOMINGO QUE LLOVIO. LAS HAGO CON GRASA DE VERDAD, NO CON ACEITE, POR ESO QUEDAN DORADITAS Y NO QUEDAN PESADAS. EL PRECIO ES POR UNIDAD Y LA DOCENA SALE 480. AVISEN UN DIA ANTES QUE LA MASA TIENE QUE DESCANSAR. RETIRAN EN CASA, EN PAYSANDU, DE MAÑANA QUE DE TARDE ESTOY EN EL JARDIN. DIOS LOS BENDIGA.",
    ubicacion: "Paysandú, Paysandú",
    publicado: "2026-05-18T11:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/feria_6.jpg",
    vendido: true,
    turbio: false,
    consultas: []
  },
  {
    id: 5456,
    vendedor: "sofi.tortasfritas",
    titulo: "Carrito de tortas fritas, hierro y chapa",
    categoria: "Varios",
    precio: 17500,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Es el carrito con el que salía a la vuelta de la feria antes de dedicarme a filmar las recetas. Estructura de hierro pintada de azul, techito para la lluvia, tapa de chapa con el hueco donde va la olla de la grasa y una rueda de bicicleta para moverlo. Los carteles que se ven en la foto te los saco y ponés los tuyos. Te lo entrego lavado. Estoy en Salto, coordino los martes que es el dia que estoy en casa cocinando.",
    ubicacion: "Salto, Salto",
    publicado: "2026-05-18T16:30:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/feria_5.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "pastelera.zuni", texto: "Estimada, lo mueve una sola persona o hay que ser dos? Muchas gracias.", fecha: "2026-05-18T20:00:00-03:00" },
      { autor: "sofi.tortasfritas", texto: "En vereda lisa lo movés sola, en el pedregullo mejor de a dos", fecha: "2026-05-19T06:40:00-03:00" },
      { autor: "pastelera.zuni", texto: "Perfecto. Lo consulto con mi sobrino que tiene camioneta. Muy amable.", fecha: "2026-05-19T09:15:00-03:00" }
    ]
  },
  {
    id: 5459,
    vendedor: "la_verdad_del_norte",
    titulo: "Bote de aluminio con trailer, papeles no tengo",
    categoria: "Varios",
    precio: 3200,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Bote de aluminio con la consola en el medio, los asientos y un motorcito atras, va con el trailer que se ve en la foto. Me lo dejó un conocido para que se lo venda, el dice que anda perfecto pero yo en el agua no lo probé ni pienso probarlo. Papeles del bote no tengo y el trailer no tiene chapa, se entrega asi como está y por eso el precio. Lo tengo parado en la puerta del local de Tacuarembo, vengan a verlo.",
    ubicacion: "Tacuarembó, Tacuarembó",
    publicado: "2026-07-23T12:30:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/nautica_2.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "coleccionista_cx", texto: "Un bote sin matrícula no lo bajás a ninguna rampa. Te lo paran antes de mojar el casco.", fecha: "2026-07-23T18:00:00-03:00" },
      { autor: "la_verdad_del_norte", texto: "yo solo revendo, no me hago responsable de lo que me traen", fecha: "2026-07-24T09:20:00-03:00" },
      { autor: "contadora.gimenez", texto: "Esa frase la leo tres veces por semana en esta feria y nunca termina bien.", fecha: "2026-07-24T15:40:00-03:00" }
    ]
  },
  {
    id: 5462,
    vendedor: "feriante_tristan",
    titulo: "Mueble de cocina con canastos para la verdura",
    categoria: "Varios",
    precio: 4900,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Mueble de caño de hierro negro con la tapa de madera lustrada y dos canastos de chapa perforada abajo, para tener la fruta y la verdura a mano y ventilada. Trae la aleta que se levanta al costado para apoyar la pava o la cafetera. Lo tenia en casa y me quedé sin lugar. Aclaro porque siempre preguntan: la fruta es mia, y el microondas y la jarra tampoco van. Precio charlable si venis con camioneta. Levanto el puesto a las 13:30, despues de esa hora no me busques.",
    ubicacion: "Cordón, Montevideo",
    publicado: "2026-05-24T08:00:00-03:00",
    contacto: "099 208 774",
    imagen: "media/fotos/electro_24.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "caro.veterinaria", texto: "Óscar, la aleta esa aguanta peso? Estoy buscando algo asi para la sala de espera.", fecha: "2026-05-24T12:20:00-03:00" },
      { autor: "feriante_tristan", texto: "aguanta lo que le pongas doctora, es la misma madera que la tapa de arriba", fecha: "2026-05-24T13:00:00-03:00" },
      { autor: "mama_de_tres_mvd", texto: "los canastos salen para lavarlos o van soldados?", fecha: "2026-05-25T21:30:00-03:00" }
    ]
  },
  {
    id: 5463,
    vendedor: "artigas_citrus",
    titulo: "Conejos criados en casa, varios",
    categoria: "Animales",
    precio: 350,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Tengo conejos que criamos en el fondo, machos y hembras. Precio por cabeza. Son mansos, mi sobrina los agarra sin problema. Estoy en Artigas, entrego en casa. Ojo que de mayo a setiembre estoy en la planta todo el dia y no contesto, escribime igual que a la noche veo.",
    ubicacion: "Artigas, Artigas",
    publicado: "2025-12-14T20:30:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/mascota_5.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "estudiante_utec", texto: "sigue disponible? ya se que el aviso es viejo", fecha: "2026-07-27T23:10:00-03:00" }
    ]
  },
  {
    id: 5465,
    vendedor: "mama_alerta_mvd",
    titulo: "Microondas blanco, anda perfecto",
    categoria: "Varios",
    precio: 2700,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Lo vendo porque me regalaron uno mas grande y en la mesada no me entran los dos. Es blanco, con el teclado de numeros y los botones de descongelar y palomitas. Anda perfecto, el plato gira parejo y la puerta cierra firme. Está un poco amarillento arriba del lado que da a la ventana. Está enchufado en la cocina como se ve en la foto, venís y lo probás antes de llevarlo. Estoy en Piedras Blancas, cerca de la placita.",
    ubicacion: "Piedras Blancas, Montevideo",
    publicado: "2026-07-13T14:20:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/electro_23.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5466,
    vendedor: "mama_de_tres_mvd",
    titulo: "Suecos de goma para nene, numero 30, sin uso",
    categoria: "Varios",
    precio: 850,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Se los trajo la abuela de afuera al mas chico y le quedaron justos, ni los estrenó, tienen la etiqueta colgando todavia como se ve en la foto. Son marrones con la carita de la grua de la pelicula de los autitos y adentro son grises. Numero 30. Los doy a menos de la mitad de lo que salieron. Estoy en Maroñas cerca de la plaza, o te los alcanzo si te queda de paso, a las 12 y media estoy en la puerta del liceo igual.",
    ubicacion: "Maroñas, Montevideo",
    publicado: "2026-03-02T18:40:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/ropa_4.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "caro.veterinaria", texto: "Andrea, si te aparecen unos del 32 avisame. El mio los rompe cada tres meses.", fecha: "2026-03-03T09:10:00-03:00" },
      { autor: "mama_de_tres_mvd", texto: "estos son 30 nomas, pero si me llega otro par te escribo!!", fecha: "2026-03-03T20:00:00-03:00" }
    ]
  },
  {
    id: 5469,
    vendedor: "melo_ferretero",
    titulo: "Malla electrosoldada galvanizada, precio por rollo",
    categoria: "Varios",
    precio: 3900,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Llegó la partida de malla electrosoldada galvanizada, la de cuadro chico. Rollo de metro cincuenta de alto por diez metros. Sirve para cerrar un gallinero, hacer jaula de conejos o para el frente de un cantero, que es para lo que la lleva todo el mundo. El precio es por rollo, llevando tres hago precio. Están en el deposito de atras tal cual la foto, sobre los pallets. Encomienda no mando, ocupa mas que un ropero. Vení, mirá y llevá.",
    ubicacion: "Melo, Cerro Largo",
    publicado: "2026-02-11T10:00:00-03:00",
    contacto: "099 641 305",
    imagen: "media/fotos/construccion_10.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5470,
    vendedor: "dona_elsa_74",
    titulo: "CABALLITO DE HAMACA DE MIS NIETOS",
    categoria: "Varios",
    precio: 1900,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "ES EL CABALLITO CON EL QUE SE HAMACABAN LOS DOS NIETOS Y YA NO LO USAN PORQUE ESTAN GRANDES. ES DE PELUCHE MARRON CON LA BASE DE MADERA, TIENE EL PAÑUELO ROJO AL CUELLO Y LA MONTURA DE CUERITO. HACIA UN RUIDITO DE RELINCHO CUANDO LE APRETABAS LA OREJA PERO SE LE ACABO LA PILA Y NO SE COMO CAMBIARSELA. LA MADERA ESTA SANA Y NO SE HAMACA PARA LOS COSTADOS. LO TENGO GUARDADO ARRIBA DEL ROPERO. ESTOY EN PAYSANDU. DIOS LOS BENDIGA.",
    ubicacion: "Paysandú, Paysandú",
    publicado: "2026-04-18T11:30:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/juguete_3.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "caro.veterinaria", texto: "Señora, la pila se cambia sacando los cuatro tornillos de abajo de la base. Es una común de las grandes.", fecha: "2026-04-18T17:00:00-03:00" },
      { autor: "dona_elsa_74", texto: "GRACIAS DOCTORA LO ANOTO EN EL CUADERNO", fecha: "2026-04-19T09:20:00-03:00" }
    ]
  },
  {
    id: 5471,
    vendedor: "caro.veterinaria",
    titulo: "Transportadora chica usada, la del consultorio",
    categoria: "Animales",
    precio: 850,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Transportadora plástica de las chicas, sirve para gato o perro de hasta ocho kilos. Es de las viejas, base marrón y tapa beige, con las trabas laterales que se encastran a presión. Aviso el defecto: la traba de arriba está floja y hay que ayudarla con la mano al cerrar, no se la lleve nadie pensando que va a viajar sola en el ómnibus. Está lavada y desinfectada. La vendo barata para que la use alguien, en la sala ya no me entra.",
    ubicacion: "Malvín, Montevideo",
    publicado: "2026-07-05T12:40:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/mascota_13.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5472,
    vendedor: "laura_rambla",
    titulo: "Dos transportadoras nuevas, sin estrenar",
    categoria: "Animales",
    precio: 1500,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Las compré para llevar los gatos de mi hermana a Rocha y al final fuimos en dos autos y quedaron adentro de la bolsa. Están nuevas, una rosada y una celeste, las dos con la puerta de reja y la traba negra de arriba. La foto es la del vendedor porque ni las saqué de la caja. El precio es de una, las dos juntas te las dejo en 2700. Estoy en Malvín, a dos cuadras de la parada del 60.",
    ubicacion: "Malvín, Montevideo",
    publicado: "2026-05-31T20:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/mascota_14.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "laura.rambla", texto: "Otra vez me escriben a mí preguntando por este aviso. No soy yo, es la otra Laura. Igual, si a alguien le sirven, ahí están.", fecha: "2026-06-01T08:30:00-03:00" }
    ]
  },
  {
    id: 5475,
    vendedor: "treintaytres_jinete",
    titulo: "Caballo overo manso, de andar",
    categoria: "Animales",
    precio: 28000,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Caballo overo colorado de siete años, manso, de andar. Sirve para trabajar en el campo o para salir a andar tranquilo un domingo. Esta domado como corresponde, sin apuros, y se ata al cabestro sin pelear, como se ve en la foto que le saqué comiendo al lado de las casas. Va con los papeles y la marca. No es el mio, el mio no lo vendo ni loco. Se ve el fin de semana en el campo cerca de Vergara.",
    ubicacion: "Treinta y Tres, Treinta y Tres",
    publicado: "2026-05-15T07:20:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/caballo_2.jpg",
    vendido: true,
    turbio: false,
    consultas: [
      { autor: "productor_durazno", texto: "aguanta jornada larga o es de paseo nomas?", fecha: "2026-05-15T18:00:00-03:00" },
      { autor: "treintaytres_jinete", texto: "aguanta el dia entero. Es caballo de trabajo, no de foto", fecha: "2026-05-16T06:00:00-03:00" }
    ]
  },
  {
    id: 5476,
    vendedor: "charrua_libre",
    titulo: "Carro jaula para hacienda, sin chapa",
    categoria: "Vehículos",
    precio: 44000,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Carro jaula de un eje, chapa y hierro, con la rampa de atras que baja entera. Entra un caballo o dos terneros. Las luces andan, la lona del piso va incluida. No tiene chapa ni empadronamiento y no lo voy a tramitar. El que lo lleva lo lleva asi. Está guardado en un predio prestado. Coordino el punto de entrega, no doy ubicacion por acá. Efectivo, de dia.",
    ubicacion: "Canelones",
    publicado: "2026-07-26T08:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/caballo_3.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "treintaytres_jinete", texto: "un carro sin chapa te lo levanta la caminera en el primer control. Eso lo sabe cualquiera que ande en la ruta", fecha: "2026-07-26T09:30:00-03:00" },
      { autor: "productor_durazno", texto: "coincido. Y el que lo compra queda con el problema encima", fecha: "2026-07-26T14:10:00-03:00" },
      { autor: "moderacion_terosocial", texto: "Aviso reportado. En revisión conforme a las normas de la comunidad.", fecha: "2026-07-28T10:00:00-03:00" }
    ]
  },
  {
    id: 5477,
    vendedor: "maldonado_inmobiliaria",
    titulo: "Sofá de tres cuerpos gris, quedó en una unidad que administramos",
    categoria: "Hogar",
    precio: 6800,
    moneda: "UYU",
    estado_articulo: "usado",
    descripcion: "Aclaramos que no es nuestro rubro: el sofá quedó en una casa que administramos y el propietario nos pidió venderlo antes de entregarla. Tres cuerpos, tapizado gris tipo gamuza, con el vivo blanco bordeando los almohadones. Los cuatro almohadones se sacan y las fundas son desenfundables. Tiene manchas de humedad en el asiento del medio y en el respaldo, la fotografía está tomada desde arriba justamente para que se aprecien. La estructura está firme y no cruje. Se retira en Maldonado con flete por cuenta del comprador. Coordinamos de lunes a viernes de 10 a 18.",
    ubicacion: "Maldonado, Maldonado",
    publicado: "2026-07-06T10:00:00-03:00",
    contacto: "consultar por acá",
    imagen: "media/fotos/mueble_21.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "nurse_valentina", texto: "esas manchas salen con limpieza a vapor o ya fue?", fecha: "2026-07-06T23:40:00-03:00" },
      { autor: "maldonado_inmobiliaria", texto: "Estimada, no lo intentamos. El valor ya contempla que hay que tapizarlo o taparlo con un cubresofá.", fecha: "2026-07-07T09:20:00-03:00" },
      { autor: "mama_de_tres_mvd", texto: "cuanto mide de largo? tengo dos metros justos contra la pared", fecha: "2026-07-09T21:00:00-03:00" },
      { autor: "maldonado_inmobiliaria", texto: "Mide 2,10 de punta a punta. En dos metros no le entra.", fecha: "2026-07-10T09:00:00-03:00" }
    ]
  },
  {
    id: 5481,
    vendedor: "costa_dorada_vecina",
    titulo: "Casa en la Costa, alquiler anual",
    categoria: "Inmuebles",
    precio: 460,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Alquilo la casa que era de mi madre. Dos dormitorios, cocina comedor, baño y un fondo grande con higuera. Fachada blanca con portón, tal como se ve en la fotografía. Pido garantía, contrato y una carta de la persona que la ocupa. Aclaro: soy sumamente amable hasta que dejo de serlo, y ese punto llega al tercer mensaje sin respuesta.",
    ubicacion: "Ciudad de la Costa, Canelones",
    publicado: "2026-04-24T16:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/casa_1.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "agua_pura_uy", texto: "el fondo tiene sol de mañana? es para la huerta", fecha: "2026-04-24T20:20:00-03:00" },
      { autor: "costa_dorada_vecina", texto: "Tiene sol de mañana y de tarde. Es lo único bueno que tiene esa casa, se lo digo con franqueza.", fecha: "2026-04-25T08:40:00-03:00" }
    ]
  },
  {
    id: 5482,
    vendedor: "el.tero.viajero",
    titulo: "Cabaña para 4 en la costa, por dia",
    categoria: "Inmuebles",
    precio: 65,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Cabaña para cuatro personas, dos ambientes, baño y kitchenette. Está sobre los médanos, a 200 metros de la bajada a la playa. Valor por dia en temporada, mínimo tres noches. Se entrega con ropa de cama. No hay wifi ni señal buena, avisamos antes porque después nos reclaman. Somos la agencia, no el fotógrafo.",
    ubicacion: "Cabo Polonio, Rocha",
    publicado: "2026-01-09T11:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/costa_3.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5486,
    vendedor: "maldonado_inmobiliaria",
    titulo: "Casa contenedor de 12 metros, lista para instalar",
    categoria: "Inmuebles",
    precio: 21500,
    moneda: "USD",
    estado_articulo: "nuevo",
    descripcion: "Módulo habitable armado sobre contenedor de 40 pies: 12 metros de largo por 2,40 de ancho, terminado y pintado. Lleva dos ventanas de aluminio con vidrio, puerta corrediza vidriada al centro, aislación en paredes y techo, instalación eléctrica embutida y baño completo. Apoya sobre bases de hormigón, como está en la foto en nuestro predio de exhibición. El traslado dentro de Maldonado va incluido, fuera del departamento se cotiza aparte. El trámite ante la intendencia lo tramita el comprador, cada padrón tiene su situación. Se muestra con hora coordinada.",
    ubicacion: "Piriápolis, Maldonado",
    publicado: "2026-02-19T10:30:00-03:00",
    contacto: "consultar por acá",
    imagen: "media/fotos/casa_8.jpg",
    vendido: false,
    turbio: false,
    consultas: []
  },
  {
    id: 5487,
    vendedor: "productor_durazno",
    titulo: "Chacra de 5 hectareas con casa, vendo",
    categoria: "Inmuebles",
    precio: 68000,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Vendo una chacra de cinco hectareas que era de mi suegro. Tiene casa de material de tres piezas, galpon de chapa y un monte de frutales. Sobre camino de tierra, a 9 km del pueblo. Padron propio y todo en regla. Vendo porque no la puedo atender, bastante tengo con lo mio. Escucho oferta razonable.",
    ubicacion: "Durazno, Durazno",
    publicado: "2026-03-30T07:10:00-03:00",
    contacto: "099 158 340",
    imagen: "media/fotos/ruta_3.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "agronomo_paysandu", texto: "que tipo de suelo tiene? si tenes el analisis te digo que le falta", fecha: "2026-03-30T12:40:00-03:00" },
      { autor: "productor_durazno", texto: "no tengo analisis. Es tierra negra, da bien la huerta", fecha: "2026-03-31T06:30:00-03:00" },
      { autor: "estudiante_utec", texto: "sigue disponible?", fecha: "2026-07-29T22:00:00-03:00" }
    ]
  },
  {
    id: 5489,
    vendedor: "treintaytres_jinete",
    titulo: "Cadena dorada con dije de guante de box",
    categoria: "Varios",
    precio: 1200,
    moneda: "UYU",
    estado_articulo: "nuevo",
    descripcion: "Se la compré a mi señora para el cumpleaños en un puesto de bijou y no le gustó, así que la vendo. Es una cadena gruesa dorada, de eslabon aplastado, con el dije del guante de box colgando. Que quede claro que no es oro, es acero dorado, a mi me la vendieron asi y asi la vendo. Está sin usar, va con la cajita. La foto es la del puesto donde la compré, no le saqué otra. La llevo a las criollas si te queda de paso o la retirás en Treinta y Tres. Los fines de semana ando en las jineteadas y no contesto.",
    ubicacion: "Treinta y Tres, Treinta y Tres",
    publicado: "2025-09-10T07:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/ruta_8.jpg",
    vendido: false,
    turbio: false,
    consultas: [
      { autor: "estudiante_utec", texto: "hola, sigue disponible? el aviso es del año pasado", fecha: "2026-06-08T23:20:00-03:00" }
    ]
  },
  {
    id: 5495,
    vendedor: "tero_anon_2018",
    titulo: "Habitacion para alquilar, no pido papeles",
    categoria: "Inmuebles",
    precio: 180,
    moneda: "USD",
    estado_articulo: "usado",
    descripcion: "Alquilo una pieza con baño compartido en una casa que estoy cuidando. No pido garantia ni recibo, se paga adelantado y en efectivo. No hago recibo tampoco. La casa no es mia, el dueño está afuera y yo quedé a cargo. Si preguntas mucho no te sirve. Entrada por el costado, la foto es la fachada.",
    ubicacion: "Paysandú, Paysandú",
    publicado: "2026-07-24T21:00:00-03:00",
    contacto: "por privado",
    imagen: "media/fotos/casa_2.jpg",
    vendido: false,
    turbio: true,
    consultas: [
      { autor: "escepticouy", texto: "Quedé a cargo no habilita a subalquilar. Eso lo sabe hasta el que quedó a cargo.", fecha: "2026-07-25T09:30:00-03:00" },
      { autor: "tero_anon_2018", texto: "es una changa nomas, no le busquen la quinta pata", fecha: "2026-07-25T18:40:00-03:00" }
    ]
  }
];
